Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/AslTables/SsdtPci.asl

The patch at "4be8625ab1b008057ae9a500aa8978be2a02d6e2
Platform/ARM/VExpressPkg: Add support for FVP RevC model"
introduced a new file SsdtPci.asl. The file SsdtPci.asl
had a few non-ASCII characters in the code comments.
These resulted in the Trim utility generating a warning
that caused the firmware build to fail on a Linux
development PC.
Therefore, remove the non-ASCII characters as it results
in builds failures on a Linux development PC.
Note: This issue was not observed on a Windows development
PC.
Signed-off-by: Sami Mujawar <sami.mujawar@arm.com>
Reviewed-by: Thomas Abraham <thomas.abraham@arm.com>

Platform/ARM/VExpressPkg: Remove non-ASCII characters

---

Platform/SiFive/U5SeriesPkg/FreedomU500VC707Board/U500.dsc
Platform/SiFive/U5SeriesPkg/FreedomU540HiFiveUnleashedBoard/U540.dsc

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3489
Fix build error of U540 and U500 caused by BdsDxe.
The edk2 patch
MdeModulePkg/BdsDxe: Update BdsEntry to use Variable Policy
requires VariablePolicyHelperLib, but U500.dsc and U540.dsc
didn't have it in the LibraryClasses section.
Cc: Abner Chang <abner.chang@hpe.com>
Cc: Gilbert Chen <gilbert.chen@hpe.com>
Cc: Daniel Schaefer <daniel.schaefer@hpe.com>
Signed-off-by: Takuto Naito <naitaku@gmail.com>
Reviewed-by: Abner Chang <abner.chang@hpe.com>

Platform/SiFive: Add VariablePolicyHelperLib to the dsc files

---

Platform/Loongson/LoongArchQemuPkg/Loongson.dsc
Platform/Loongson/LoongArchQemuPkg/Loongson.fdf

Add VGA graphics card support for Loongarch,
VGA graphics cards have GOP to support early
kernel information printing, so we need it.
Cc: Ard Biesheuvel <ardb+tianocore@kernel.org>
Signed-off-by: xianglai li <lixianglai@loongson.cn>

Platform/Loongson: Support vga for loongarch.

---

Platform/Loongson/LoongArchQemuPkg/Loongson.dsc

Some toolchains have stack protection enabled by default, so without the appropriate library included the build will fail with missing symbols during link.
Mail thread with reviews: https://edk2.groups.io/g/devel/message/100746
Cc: devel@edk2.groups.io
Reviewed-by: Chao Li <lichao@loongson.cn>
Reviewed-by: Xianglai Li <lixianglai@loongson.cn>

Platform/Loongson: Allow building with stack protector support

---

Platform/Loongson/LoongArchQemuPkg/PlatformPei/MemDetect.c
Platform/Loongson/LoongArchQemuPkg/PlatformPei/PlatformPei.inf

When 0 address protection is enabled,
0-4k memory needs to be preallocated to
prevent UEFI applications from allocating use,
such as grub.
Cc: Ard Biesheuvel <ardb+tianocore@kernel.org>

Platform/Loongson: Pre-allocate 0-4K memory during the Pei phase

---

Platform/Intel/Tools/GenBiosId/GenBiosId.py

The length of the Board ID is being updated based on the BOARD_ID string. If the PCH_TYPE is empty space/single quotes(''), removing the empty space/single quotes('') and concatenating the TARGET_PLATFORM_SHORT and BUILD flag strings.
Cc: Bob Feng <bob.c.feng@intel.com>
Cc: Yuwei Chen <yuwei.chen@intel.com>
Cc: T V Krishnamoorthy <krishnamoorthy.t.v@intel.com>
Reviewed-by: Bob Feng <bob.c.feng@intel.com>

Platform/Intel: Enhance the BOARD_ID without PCH_TYPE support

---

Platform/Loongson/LoongArchQemuPkg/Loongson.dsc

Adding a reference to AcpiPlatformLib to the dsc file as loongarch is used to fix compilation errors.
Cc: Ard Biesheuvel <ardb+tianocore@kernel.org>

Platform/Loongson: Add AcpiPlatformLib to fix compile error

---

Platform/Sophgo/SG2042_EVB_Board/SG2042.dsc

Disable CMO and Sstc features because they are not supported by the platform. And use SBI calls itself by default for Sophgo SG2042 platform.
Cc: dahogn <dahogn@hotmail.com>
Cc: meng-cz <mengcz1126@gmail.com>
Cc: USER0FISH <libing1202@outlook.com>
Reviewed-by: Sunil V L <sunilvl@ventanamicro.com>

Sophgo/SG2042Pkg: Disable CMO and Sstc features

---

Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCoreDxe/IntelVTdCoreDxe.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdDxe/IntelVTdDxe.c

When PcdVTdPolicyPropertyMask BIT2 is set and ACPI DMAR table is not ready, It is no need to hit an assert, and just returns EFI_NOT_READY.
Reviewed-by : Jenny Huang <jenny.huang@intel.com>
Cc: Ray Ni <ray.ni@intel.com>
Cc: Rangasai V Chaganty <rangasai.v.chaganty@intel.com>
Cc: Chiang Chris <chris.chiang@intel.com>

IntelSiliconPkg/VTd: Remove ASSERT in VTdSetAttribute

---

Platform/Loongson/LoongArchQemuPkg/Library/NorFlashQemuLib/NorFlashQemuLib.c
Platform/Loongson/LoongArchQemuPkg/Library/NorFlashQemuLib/NorFlashQemuLib.inf
Platform/Loongson/LoongArchQemuPkg/Loongson.fdf

The current implementation of loongarch NorFlashQemuLib is to parse fdt and think that the first flash address resolved to the NVRAM space, with the evolution of qemu code, loongarch uses the first flash to store UEFI code and the second flash as NVRAM space, so NorFlashQemuLib needs to be able to parse multiple flash base addresses. By default, the first piece of flash other than UEFI code is considered as NVRAM space.
Cc: Andrea Bolognani <abologna@redhat.com>

Platform/Loongson: loongarch supports parsing multi-chip flash

---

Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCoreDxe/VtdReg.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCorePei/IntelVTdDmar.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdDmarPei/IntelVTdDmar.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdDxe/VtdReg.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdPmrPei/VtdReg.c
Silicon/Intel/IntelSiliconPkg/Library/IntelVTdPeiDxeLib/IntelVTdPeiDxeLib.c

Here is the process of modify GCMD_REG.
Read GSTS_REG
Reset the one-shot bits.
Modify the target comamnd value.
Write the command value to GCMD_REG.
Wait until GSTS_REG indicates command is serviced.
Cc: Ray Ni <ray.ni@intel.com>
Cc: Rangasai V Chaganty <rangasai.v.chaganty@intel.com>
Cc: Jenny Huang <jenny.huang@intel.com>

IntelSiliconPkg/VTd: Reset the one-shot bits before modifing GCMD_REG

---

Platform/BeagleBoard/BeagleBoardPkg/PrePi/PeiUniCore.inf
Platform/BeagleBoard/BeagleBoardPkg/PrePi/PrePi.h
Platform/Intel/SimicsOpenBoardPkg/SecCore/SecMain.c
Platform/Intel/SimicsOpenBoardPkg/SecCore/SecMain.inf
Platform/Loongson/LoongArchQemuPkg/Sec/SecMain.c
Platform/Loongson/LoongArchQemuPkg/Sec/SecMain.inf
Silicon/Sophgo/SG2042Pkg/Sec/Memory.c
Silicon/Sophgo/SG2042Pkg/Sec/SecMain.h
Silicon/Sophgo/SG2042Pkg/Sec/SecMain.inf

https://edk2.groups.io/g/devel/message/116378
msgid `<20240305120126.70259-1-lersek@redhat.com>`
~~~
Bugzilla:
- https://bugzilla.tianocore.org/show_bug.cgi?id=990
This patch series puts the recent BaseTools feature to use in which
AutoGen generates the ProcessLibraryConstructorList() declaration in
"AutoGen.h" for such non-library SEC modules whose INF_VERSION is at
least 1.30. The BaseTools feature is present in both edk2 [1] and
edk2-basetools [2], and has been documented in the Build spec [3] and
the Inf spec [4]. Kudos to Rebecca for tagging a new edk2-basetools
release [5] [6] with the new feature.
[1] edk2 commit bac9c74080cf
[2] edk2-basetools commit 5b7161de22ee
[3] edk2-BuildSpecification commit range db69f5661cae..7a7165a7d199
[4] edk2-InfSpecification commit range …

 [edk2-platforms PATCH v2 0/4] clean up ProcessLibraryConstructorList() declarations in SEC modules

---

Silicon/Sophgo/SG2042Pkg/Sec/Memory.c

Adapting memory addresses may not start from 0x0,
for example, the starting memory address starts
from 0x8000_0000.
I understand: LowestMemBase is the lowest DDR
address in the system.
UefiMemoryBase = LowestMemBase +
CodeSize(opensbi+UEFI);
LowestMemSize -= CodeSize(UefiMemoryBase -
LowestMemBase)
Cc: Sunil V L <sunilvl@ventanamicro.com>
Cc: USER0FISH <libing1202@outlook.com>
Cc: caiyuqing379 <caiyuqing_hz@outlook.com>
Cc: dahogn <dahogn@hotmail.com>
Cc: meng-cz <mengcz1126@gmail.com>
Reviewed-by: Sunil V L <sunilvl@ventanamicro.com>
Reviewed-by: Jingyu Li <jingyu.li01@sophgo.com>

SG2042Pkg/Sec:Modify Calculation LowestMemSize

---

Platform/Loongson/LoongArchQemuPkg/Loongson.dsc

QemuFwCfgLibMmio has been removed,
using the latest FwCfgLib to fix compilation errors
Cc: Gerd Hoffmann <kraxel@redhat.com>

Platform/Loongson: Fix compile error

---

Platform/AMD/AmdPlatformPkg/AmdPlatformPkg.dec
Platform/AMD/AmdPlatformPkg/AmdPlatformPkg.dsc
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/DefaultLomDevicePath.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/SmbiosCommon.h
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/SmbiosCommonDxe.inf
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/SmbiosCommonEntryPoint.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type11OemStringsFunction.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type12SystemCfgOptionsFunction.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type13BiosLanguageInfoFunction.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type38IpmiDeviceInformation.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type41OnboardDevExtInfoFunction.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type8PortConnectorInfoFunction.c
Platform/AMD/AmdPlatformPkg/Universal/SmbiosCommonDxe/Type9SystemSlotInfoFunction.c

Adds SMBIOS common driver which generates various
tables for AMD platforms.
Cc: Paul Grimes <paul.grimes@amd.com>
Reviewed-by: Abner Chang <abner.chang@amd.com>

AmdPlatformPkg: Adds SmbiosCommonDxe driver

---

Platform/AMD/AmdPlatformPkg/AmdPlatformPkg.dsc
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcInternal.c
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcInternal.h
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLib.c
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLib.uni
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLibDxe.c
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLibDxe.inf
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLibSmm.c
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcPlatformLibSmm.inf
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcSmmState.c
Platform/AMD/AmdPlatformPkg/Library/SpiHcPlatformLib/SpiHcSmmState.h

Implements SpiHcPlatformLib library for AMD platform. Its AMD platform specific SPI host controller library.
Cc: Abner Chang <abner.chang@amd.com>
Cc: Paul Grimes <paul.grimes@amd.com>

AmdPlatform/SpiHcPlatformLib: Implements SpiHcPlatformLib library

---

Platform/Loongson/LoongArchQemuPkg/Loongson.dec
Platform/Loongson/LoongArchQemuPkg/Loongson.dsc
Platform/Loongson/LoongArchQemuPkg/PlatformPei/MemDetect.c
Platform/Loongson/LoongArchQemuPkg/PlatformPei/PlatformPei.inf

Temparory stack memory on PEI is hardcoded now, also minimium memory size 256M is hardcoded now. Here memory map table from fw cfg can be parsed. If there is memory map entry contains pei stack, it can be published as usable memory at PEI stage.

Platform/Loongson: Remove minimium memory size limitation

---

Silicon/Intel/IntelSiliconPkg/Include/IndustryStandard/FirmwareInterfaceTable.h

This commit includes below changes,
(1) Add the below definition for FIT entry type
- FIT_TYPE_03_DIAGNOSTIC_ACM
- FIT_TYPE_05_MMC_FIRMWARE_IMAGE
- FIT_TYPE_06_FIT_RESET_STATE
- FIT_TYPE_1A_VAB_PROVISIONING_TABLE
- FIT_TYPE_1B_VAB_KEY_MANIFEST
- FIT_TYPE_1C_VAB_IMAGE_MANIFEST
- FIT_TYPE_1D_VAB_IMAGE_HASH_DESC
- FIT_TYPE_2C_SACM_DEBUG
- FIT_TYPE_2E_GRANULAR_SCRTM_ERROR
(2) Add the below definition to support FIT table range
- FIT_TABLE_LOWER_ADDRESS
- FIT_TABLE_UPPER_ADDRESS
(3) Add the below definition and structure for Type02 (Ver. 0x200) entry
- FIT_TYPE_02_VERSION_200
- FIT_TYPE_02_VERSION_200_ENTRY

IntelSiliconPkg: Update Header File to Align FIT Specification 1.5

---

Platform/Intel/SimicsOpenBoardPkg/BoardX58Ich10/OpenBoardPkgPcd.dsc

This patch is to enable the PcdSmrrEnable since the simics report it has the capability to enable the smrr.

Platform/Intel: Enable the PcdSmrrEnable

---

Silicon/Intel/SimicsIch10Pkg/Spi/Smm/PchSpi.c
Silicon/Intel/SimicsIch10Pkg/Spi/Smm/PchSpi.h
Silicon/Intel/SimicsIch10Pkg/Spi/Smm/PchSpiStandaloneMm.inf

This patch Add a new PchSpiStandaloneMm.inf driver for the PCH SPI Interface support.

Silicon/Intel: Support MM_STANDALONE for the PCH SPI Interface

---

Platform/AMD/AmdPlatformPkg/AmdPlatformPkg.dsc
Platform/AMD/AmdPlatformPkg/DynamicTables/Library/Acpi/AcpiFadtLib/AcpiFadtLib.c
Platform/AMD/AmdPlatformPkg/DynamicTables/Library/Acpi/AcpiFadtLib/AcpiFadtLib.inf

Creates ACPI FADT table during boot time.
Cc: Abner Chang <abner.chang@amd.com>
Cc: Paul Grimes <paul.grimes@amd.com>

AmdPlatformPkg/DynamicTables: Creates ACPI FADT table

---

Features/ManageabilityPkg/Include/Manageability.dsc
Features/ManageabilityPkg/Include/Protocol/IpmiBlobTransfer.h
Features/ManageabilityPkg/ManageabilityPkg.dec
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/InternalIpmiBlobTransfer.h
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/IpmiBlobTransferDxe.c
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/IpmiBlobTransferDxe.inf
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/Readme.md
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/UnitTest/IpmiBlobTransferTestUnitTests.c
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/UnitTest/IpmiBlobTransferTestUnitTestsHost.inf

This change implements the blob transfer protocol used in OpenBmc documented here: https://github.com/openbmc/phosphor-ipmi-blobs
Cc: Abner Chang <abner.chang@amd.com>
Cc: Isaac Oram <isaac.w.oram@intel.com>
Cc: Abdul Lateef Attar <AbdulLateef.Attar@amd.com>
Cc: Nickle Wang <nicklew@nvidia.com>

ManageabilityPkg: add support for the phosphor ipmi blob transfer protocol

---

Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCoreDxe/BmDma.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCoreDxe/VtdLog.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdCorePei/IntelVTdCorePei.c
Silicon/Intel/IntelSiliconPkg/IntelSiliconPkg.dsc

Some libraries and modules are missing from the build.
The first patch fixes compiler and linker failures. The second patch
adds the missing components to IntelSiliconPkg.dsc.
---
> Note: An attempt was made to follow the coding style used in
> the files which differs slightly from coding style used in
> edk2 such as spaces between casts.

IntelSiliconPkg: Add missing components and build fixes

---

Silicon/Intel/IntelSiliconPkg/Include/IndustryStandard/IgdOpRegion32.h

- Backlight related fields in MBOX2 has uncalibrated brightness support
- Valid Bit added for BCL in MBOX2

IntelSiliconPkg: Add IgdOpRegion32.h to support IGD OpRegion v3.2

---

Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Marvell/OdysseyPkg/OdysseyPkg.fdf
Silicon/Marvell/OdysseyPkg/OdysseyPkg.dsc.inc

After rebasing on top of tree, the Odyssey platform required adjustments to allow successful build.

Odyssey build fixes

---

Maintainers.txt

The following individuals are no longer active maintainers:
- Kelly Steele
- Zailiang Sun

Maintainers.txt: Cleanup inactive maintainers.

---

Silicon/Intel/Tools/FitGen/FitGen.c
Silicon/Intel/Tools/FitGen/FitGen.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4828
Support Type5 for Memory Microcontroller Firmware Image entry.
Cc: Yuwei Chen <yuwei.chen@intel.com>
Cc: Feng Bob C <bob.c.feng@intel.com>

Silicon/Intel/FitGen：FIT change for MMC entry.

---

Silicon/Qemu/SbsaQemu/Library/SbsaQemuLib/SbsaQemuLib.c

ArmPlatformIsPrimaryCore() was removed in
8676e88233d41323ed3b3a9087288e83cc87ebf7 commit:
> Remove all the ArmPlatformLib routines that are no longer used now
> that the MPCore SEC drivers have been retired. The prototypes will be
> removed from the ArmPlatformLib library class in a subsequent EDK2
> change.

SbsaQemu: ArmPlatformIsPrimaryCore code is gone

---

.github/workflows/AssignReviewers.yml

Move from v2 to v4 gets rid of warnings present in each workflow run:
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2.
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v2,

Github workflow: update actions/checkout to latest

---

Platform/BeagleBoard/BeagleBoardPkg/Library/BeagleBoardLib/BeagleBoardHelper.S
Platform/BeagleBoard/BeagleBoardPkg/PrePi/PrePi.c

Copy ArmLib set/way cache maintenance code into beagle, which is the only remaining user

Beagle setway dcache maintenance

---

Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/Morello/MorelloPlatformFvp.dsc
Platform/ARM/N1Sdp/N1SdpPlatform.dsc
Platform/ARM/SgiPkg/RdE1Edge/RdE1Edge.dsc
Platform/ARM/SgiPkg/RdN1Edge/RdN1Edge.dsc
Platform/ARM/SgiPkg/RdN1EdgeX2/RdN1EdgeX2.dsc
Platform/ARM/SgiPkg/RdN2/RdN2.dsc
Platform/ARM/SgiPkg/RdN2Cfg1/RdN2Cfg1.dsc
Platform/ARM/SgiPkg/RdN2Cfg2/RdN2Cfg2.dsc
Platform/ARM/SgiPkg/RdN2Cfg3/RdN2Cfg3.dsc
Platform/ARM/SgiPkg/RdV1/RdV1.dsc
Platform/ARM/SgiPkg/RdV1Mc/RdV1Mc.dsc
Platform/ARM/SgiPkg/RdV3/RdV3.dsc
Platform/ARM/SgiPkg/Sgi575/Sgi575.dsc
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc

Juno's RngLib implementation is:
- BaseRngLib.inf if a secure RngLib is enforced
- BaseRngLibTimerLib.inf if a non-secure RngLib is tolerated
BaseRngLib.inf relies on the Arm's RNDR instruction. The instruction
returns a DRBG-generated random number. The DRBG used is considered
as secure.
The RNDR instruction is available if FEAT_RNG is set. The Juno doesn't
support it.
When security is enforced (i.e. ENABLE_UNSAFE_RNGLIB is not set),
the Juno cannot generate secure random numbers through the RngLib.
Secure random numbers could be generated by using the Juno's TRNG.
This can be done by:
- using the RngDxeLib implementation of the RngLib
- RngDxeLib relies on the RngDxe
- the RngDxe has access to the TRNG

 Platform/ARM/Juno: Use RngDxeLib

---

CODEOWNERS
REVIEWERS

Move myself (@bcran) from a reviewer of Ampere code to a maintainer role.

CODEOWNERS: Move @bcran from reviewer to maintainer role

---

CODEOWNERS
REVIEWERS

This updates Chuong's role from reviewer to maintainer as he has consistently contributed to the project through active reviews, valuable feedback, and continuous improvement efforts.

CODEOWNERS: Move @chuongtranle from reviewer to maintainer

---

Platform/Intel/MinPlatformPkg/Include/Dsc/MinPlatformFeaturesPcd.dsc.inc

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4853
When the PcdStandaloneMmEnable FeaturePcd was added, it was not added to MinPlatformFeaturesPcd.dsc.inc
Because of this, any existing BoardPkg that does not have Standalone MM support will no longer build because the default value of FALSE is not declared during DSC parsing.
The fix is to add the PCD to MinPlatformFeaturesPcd.dsc.inc

Addition of PcdStandaloneMmEnable has broken build of BoardPkg(s)

---

Platform/Intel/AlderlakeOpenBoardPkg/AlderlakePRvp/OpenBoardPkg.dsc
Platform/Intel/CometlakeOpenBoardPkg/CometlakeURvp/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/AspireVn7Dash572G/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/GalagoPro3/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/KabylakeRvp3/OpenBoardPkg.dsc
Platform/Intel/QuarkPlatformPkg/Quark.dsc
Platform/Intel/QuarkPlatformPkg/QuarkMin.dsc
Platform/Intel/TigerlakeOpenBoardPkg/TigerlakeURvp/OpenBoardPkg.dsc
Platform/Intel/WhiskeylakeOpenBoardPkg/UpXtreme/OpenBoardPkg.dsc
Platform/Intel/WhiskeylakeOpenBoardPkg/WhiskeylakeURvp/OpenBoardPkg.dsc
Platform/Intel/WhitleyOpenBoardPkg/PlatformPkg.dsc

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4854
Build issues are currently seen on Intel platforms due to PR tianocore/edk2#5957. This PR introduces the requirement for any instance of SecCore to include StackCheckLibNull, which is not currently included on Intel platform builds.
The fix is to add this library to SecCore.

Build failure with Intel platforms on VS2019

---

Platform/RaspberryPi/RPi4/RPi4.dsc
Platform/RaspberryPi/RPi4/RPi4.fdf
Platform/RaspberryPi/RPi4/Readme.md

The Pi's UEFI image was sized without thought for much future growth, and its become apparent that its largly outgrown the allocated space when various debug options or edk2 featurees are enabled. Since these images tend to exist on disks which are usually in the GB+ ranges doubling the size of the RPI_EFI.fd image shouldn't be a problem.
This change must be accompanied by build edk2-non-osi changes to TFA which update the RPI3_PRELOADED_DTB_BASE=0x3f0000 and config.txt changes as documented in the README being patched.
Since we are adjusting the image size, lets reserve a 64k block for future PCC channel data structures that are shared between TFA and ACPI as well immediately before the DTB.

Platform/RPi4: Allocate more space for UEFI image

---

Platform/Intel/AlderlakeOpenBoardPkg/AlderlakePRvp/Library/BoardInitLib/Pei/PeiInitPreMemLib.c
Platform/Intel/AlderlakeOpenBoardPkg/FspWrapper/Library/SecFspWrapperPlatformSecLib/SecRamInitData.c
Platform/Intel/AlderlakeOpenBoardPkg/OpenBoardPkg.dec
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/DxeSiliconPolicyUpdateLib/DxeSaPolicyInit.c
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/PeiPolicyUpdateLib/PeiCpuPolicyUpdatePreMem.c
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/PeiPolicyUpdateLib/PeiPchPolicyUpdate.c
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/PeiPolicyUpdateLib/PeiSaPolicyUpdate.c
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/PeiPolicyUpdateLib/PeiSaPolicyUpdatePreMem.c
Platform/Intel/build.cfg
Platform/Intel/build_bios.py
Silicon/Intel/AlderlakeSiliconPkg/Fru/AdlCpu/LibraryPrivate/BaseCpuInfoFruLib/BaseCpuInfoFruLib.c
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Gpio/Library/PeiDxeSmmGpioLib/PeiDxeSmmGpioLib.inf
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Spi/IncludePrivate/Library/SpiCommonLib.h
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Spi/Library/PeiSpiLib/PchSpi.c
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Spi/LibraryPrivate/BaseSpiCommonLib/SpiCommon.c
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Spi/Smm/Spi.c
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/Spi/Smm/SpiSmm.inf
Silicon/Intel/AlderlakeSiliconPkg/Pch/PchSmiDispatcher/Smm/PchSmmCore.c
Silicon/Intel/AlderlakeSiliconPkg/Pch/PchSmiDispatcher/Smm/PchSmmGpi.c

This patch series enables Linux GCC builds on AlderlakeOpenBoardPkg.

Enable Linux GCC builds on AlderlakeOpenBoardPkg

---

Features/ManageabilityPkg/Library/IpmiCommandLib/IpmiCommandLibPei.inf

This introduces IpmiCommandLib/IpmiCommandLibPei.inf for the support of the IPMI command library in PEI. It is consistent with the IpmiLib which has supported separately an instance in PEI.
**Side-Note**: Ampere Mt. Jade will use this library instance.

ManageabilityPkg: Add IpmiCommandLib PEI instance

---

Silicon/Ampere/AmpereAltraPkg/AcpiCommonTables/Fadt.aslc

Set the EFI_ACPI_6_3_LOW_POWER_S0_IDLE_CAPABLE flag in the FADT.
The ACPI specification says the LOW_POWER_S0_IDLE_CAPABLE flag means that the platform is able to achieve power savings in S0 similar to or better than those typically in S3. It effectively means that the system will not achieve any power savings by transitioning to S3. Since Altra doesn't support the S3 state, set this flag.
This resolves the FWTS S0idleNoFADT error.

Silicon/Ampere: Set EFI_ACPI_6_3_LOW_POWER_S0_IDLE_CAPABLE in FADT

---

Platform/Intel/BoardModulePkg/BoardModulePkg.dec
Platform/Intel/BoardModulePkg/Test/BoardModulePkgHostTest.dsc
Platform/Intel/BoardModulePkg/Test/Mock/Include/GoogleTest/Library/MockBiosIdLib.h
Platform/Intel/BoardModulePkg/Test/Mock/Library/GoogleTest/MockBiosIdLib/MockBiosIdLib.cpp
Platform/Intel/BoardModulePkg/Test/Mock/Library/GoogleTest/MockBiosIdLib/MockBiosIdLib.inf

Added a gmock for GoogleTests that pull in BiosIdLib.
Original PR: https://github.com/microsoft/mu_common_intel_min_platform/pull/261/files

BoardModulePkg: Added Mock library for BiosIdLib

---

Silicon/Intel/IntelSiliconPkg/Feature/SmmAccess/Library/PeiSmmAccessLib/PeiSmmAccessLib.c
Silicon/Intel/IntelSiliconPkg/Feature/SmmAccess/SmmAccessDxe/SmmAccessDriver.c
Silicon/Intel/IntelSiliconPkg/Feature/VTd/IntelVTdDmarPei/IntelVTdDmarPei.c

**Two commits:**
---
**IntelSiliconPkg/IntelVTdDmarPei: Prevent invalid dereference**
Prevent invalid DMAR ACPI table dereference if the table is not
found.
---
**IntelSiliconPkg/SmmAccess: Fix potential integer overflow in loop comparison**
SmmAccessDxe:
`mSmmAccess.NumberRegions` is a `UINTN` while the loop index variable
compared against it is a `UINT8`. This can lead to an overflow of the
loop index for `mSmmAccess.NumberRegions` for values larger than
`UINT8_MAX`. This change makes `Index` a `UINTN` to match in width.
PeiSmmAccessLib:
Fixes a similar `UINT8` loop index issue.

IntelSiliconPkg: Code Quality Improvements

---

Platform/RaspberryPi/Drivers/RpiFirmwareDxe/RpiFirmwareDxe.c

Fetching the real serial number on Raspberry Pi 4 was not working due to compiler optimization / struct padding.
Related to comment in https://github.com/tianocore/edk2-platforms/blob/6cfae9dac2ec4d99a10c9efd6d20a521904931fe/Platform/RaspberryPi/Drivers/RpiFirmwareDxe/RpiFirmwareDxe.c#L395-L396
After this change, the reported serial number will be the actual board serial number and not the MAC address – so this would be a breaking change.
```diff
cat /sys/class/dmi/id/board_serial
-0000E4xxxxxxxx5F
+10000000Dxxxxxx1
```
---
Tested on RPi 4B 8G Rev 1.4 & 1.5.

RaspberryPi/RPiFirmwareDxe: Use the real serial number on RPi4

---

Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Silicon/Qemu/SbsaQemu/Drivers/SbsaQemuAcpiDxe/SbsaQemuAcpiDxe.c
Silicon/Qemu/SbsaQemu/Drivers/SbsaQemuSmbiosDxe/SbsaQemuSmbiosDxe.c

I ran FirmWare Test Suite and it gave me two errors:
- IORT
```
FAILED [HIGH] IORTMemAttrInvalid: Test 1, IORT PCI Root Complex Node Memory
Attributes are illegal, CCA cannot be 1 if CPM is 0.
```
- SMBIOS
```
FAILED [HIGH] DMIBadTableLength: Test 3, Type 17 expects length of 0x5c, has
incorrect length of 0x64
```
This branch fixes both of them. Also updates IORT to E.f version of specification.

SbsaQemu: fix FWTS errors

---

Platform/Intel/MinPlatformPkg/MinPlatformPkg.dec

FSP-I Base/Size/Offset PCD is used in fdf file to define FSP-SMM FV Base/Size/Offset in the flash map.

MinPlatformPkg : Add PCD for FSP-I Base/Size/Offset

---

Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/FspSupport.c
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/FspSupportNull.c
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/PlatformInitPreMem.c
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/PlatformInitPreMemNonFsp.inf

Provide a PlatformInitPreMemNonFsp that non Intel platforms can consume it to use PlatformInitPreMem without adding Intel specific packages as dependency.

MinPlatformPkg: Isolate FSP dependency for PlatformInitPreMem

---

CODEOWNERS
CONTRIBUTORS.md

I recently moved from the GitHub account @bcran to @bexcran. Update CODEOWNERS and CONTRIBUTORS.md.

Update CODEOWNERS and CONTRIBUTORS.md with my new GitHub username

---

Drivers/OptionRomPkg/OptionRomPkg.dec
Drivers/OptionRomPkg/OptionRomPkg.dsc
Drivers/OptionRomPkg/RenesasFirmwarePD720202/README.md
Drivers/OptionRomPkg/RenesasFirmwarePD720202/RenesasFirmwarePD720202.c
Drivers/OptionRomPkg/RenesasFirmwarePD720202/RenesasFirmwarePD720202.inf

Add the Renesas uPD720202 firmware loader based on Ard Biesheuvel's patch at
https://edk2.groups.io/g/devel/topic/patch_optionrompkg_add/30905893#
The uPD72020x USB 3.0 chipset family supports two modes of operation. Either the firmware is stored in an external EEPROM chip and downloaded into the chipset at boot time, or it must be uploaded into the chipset by the operating system / driver.
The second option always works and overrides any firmware stored into the EEPROM of the card.
More technical details are discussed in a blog post at https://mjott.de/blog/881-renesas-usb-3-0-controllers-vs-linux.

Drivers/OptionRomPkg: Add Renesas uPD720202 firmware loader

---

Features/ManageabilityPkg/Include/Manageability.dsc
Features/ManageabilityPkg/Include/PostMemory.fdf
Features/ManageabilityPkg/ManageabilityPkg.dec
Features/ManageabilityPkg/ManageabilityPkg.dsc
Features/ManageabilityPkg/Universal/IpmiBlobTransferDxe/IpmiBlobTransferDxe.c
Features/ManageabilityPkg/Universal/IpmiProtocol/Smm/IpmiProtocolSmm.inf
Features/ManageabilityPkg/Universal/IpmiSmbiosTransferDxe/IpmiSmbiosTransferDxe.c
Features/ManageabilityPkg/Universal/IpmiSmbiosTransferDxe/IpmiSmbiosTransferDxe.inf
Features/ManageabilityPkg/Universal/PldmSmbiosTransferDxe/PldmSmbiosTransferDxe.c

Add IpmiSmbiosTransferDxe driver to ManageabilityPkg. This enables the ability of sending SMBIOS table to BMC by using IPMI Blob transfer protocol.
I also fixed several build issues observed on GCC5 build.

ManageabilityPkg/IpmiSmbiosTransferDxe: add support of sending SMBIOS table to BMC

---

Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c

Clang build fails with the below warning:
|  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:216:11: error: variable
|    'FileSize' is used uninitialized whenever 'if' condition is false
|    [-Werror,-Wsometimes-uninitialized].
|                if (FileHandle != NULL) {
|                    ^~~~~~~~~~~~~~~~~~
|  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:281:38: note:
|    uninitialized use occurs here.
|            WriteBackDataCacheRange (FileData, FileSize);
|                                               ^~~~~~~~
|  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:136:39: note: initialize
|    the variable 'FileSize' to silence this warning
|            UINTN                       FileSize;
|                                                ^
| …

Platform/ARM/ArmShellCmdRunAxf: Fix build with clang

---

Platform/Bosc/XiangshanSeriesPkg/NanhuDev/NanhuDev.dsc
Platform/Bosc/XiangshanSeriesPkg/NanhuDev/NanhuDev.fdf
Platform/RISC-V/PlatformPkg/Include/RiscVBitOp.h
Platform/RISC-V/PlatformPkg/RiscVPlatformPkg.dec
Silicon/Bosc/NanHuPkg/Library/PciHostBridgeLib/PciHostBridgeLib.c
Silicon/Bosc/NanHuPkg/Library/PciHostBridgeLib/PciHostBridgeLib.h
Silicon/Bosc/NanHuPkg/Library/PciHostBridgeLib/PciHostBridgeLib.inf
Silicon/Bosc/NanHuPkg/Library/PciSegmentLib/PciSegmentLib.c
Silicon/Bosc/NanHuPkg/Library/PciSegmentLib/PciSegmentLib.inf

In order to support PCIe host driver on the Silicon/BOSC NanhuDev platform。
Three patches have been submitted, with the following functions:
7dcf45f: Add PCI Segment Library for Silicon/Bosc NanHuDev platform.
8f8ae61：Add  PciHostBridgeLib driver for Silicon/Bosc NanHuDev platform.  
6764dc4: Add Support NVME device 
Reviewed-by: Evan Chai <evan.chai@linux.alibaba.com>
Reviewed-by: Ran Wang <wangran@bosc.ac.cn>
Reviewed-by: Jian Zhang <zhangjian@bosc.ac.cn>
Cc: Sunil V L <sunilvl@ventanamicro.com>
Cc: Daniel Schaefer <git@danielschaefer.me>
Cc: Ray Ni <ray.ni@intel.com>

Silicon/Bosc: Add Support pcie driver to NanHuDev

---

Platform/Ampere/JadePkg/JadeLinuxBoot.dsc
Platform/Ampere/JadePkg/JadeLinuxBoot.fdf
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc

This adds DSC and FDF files to build EDK2+LinuxBoot image.
Create workspace and clone the following repositories into the workspace.
* https://github.com/tianocore/edk2
* https://github.com/tianocore/edk2-platforms
* https://github.com/tianocore/edk2-non-osi
* https://github.com/linuxboot/linuxboot
```
cd linuxboot/mainboards/ampere/jade
make fetch flashkernel
```
```
export WORKSPACE=$PWD
export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi:$PWD/edk2-platforms/Features
make -C edk2/BaseTools
. edk2/edksetup.sh && build -a AARCH64 -t GCC -b RELEASE -n$(nproc) \
-D LINUXBOOT_FILE=linuxboot/mainboards/ampere/jade/flashkernel \
-p edk2-platforms/Platform/Ampere/JadePkg/JadeLinuxBoot.dsc
```

Ampere: Add DSC/FDF files to support LinuxBoot

---

Platform/Intel/MinPlatformPkg/MinPlatformPkg.dsc
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/FspSupport.c
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/FspSupportNull.c
Platform/Intel/MinPlatformPkg/PlatformInit/PlatformInitPei/PlatformInitPreMemNonFsp.inf

Apply minor fixes for #224. This PR includes:
- Add missing copyright header for new files
- Add a blank line at the end of new files
- Add inf instance in `Platform\Intel\MinPlatformPkg\MinPlatformPkg.dsc` for unit test purpose.

Minor fixes for #224

---

Drivers/DisplayLink/DisplayLinkPkg/DisplayLinkGop/Gop.c
Platform/ARM/JunoPkg/Library/HdLcdArmJunoLib/HdLcdArmJuno.c
Platform/ARM/JunoPkg/Library/JunoPciHostBridgeLib/JunoPciHostBridgeLib.c
Platform/ARM/Morello/Library/PlatformLib/PlatformLibMem.c
Platform/ARM/VExpressPkg/Library/ArmVExpressPciHostBridgeLib/ArmVExpressPciHostBridgeLib.c
Platform/Hisilicon/Library/PciHostBridgeLib/PciHostBridgeLib.c
Platform/RaspberryPi/Drivers/MmcDxe/MmcDebug.c
Silicon/AMD/Styx/Library/AmdStyxLib/StyxMem.c
Silicon/Intel/AlderlakeSiliconPkg/IpBlock/P2sb/Library/PeiDxeSmmPchPcrLib/PchPcrLib.c
Silicon/Intel/CoffeelakeSiliconPkg/Pch/Library/PeiDxeSmmPchPcrLib/PchPcrLib.c
Silicon/Intel/CoffeelakeSiliconPkg/Pch/Library/PeiPchPolicyLib/PchPrintPolicy.c
Silicon/Intel/KabylakeSiliconPkg/Pch/Library/PeiDxeSmmPchInfoLib/PchInfoLib.c
Silicon/Intel/KabylakeSiliconPkg/Pch/Library/PeiPchPolicyLib/PchPrintPolicy.c
Silicon/Intel/TigerlakeSiliconPkg/IpBlock/P2sb/Library/PeiDxeSmmPchPcrLib/PchPcrLib.c
Silicon/Marvell/Drivers/Gpio/MvGpioDxe/MvGpioDxe.c
Silicon/Marvell/Drivers/Gpio/MvPca95xxDxe/MvPca95xxDxe.c
Silicon/NXP/Library/PciHostBridgeLib/PciHostBridgeLib.c
Silicon/Sophgo/SG2042Pkg/Drivers/MmcDxe/MmcDebug.c

edk2 commit [ae83c6b7fd83a5906e016a32027c1bcd792a624e](https://github.com/tianocore/edk2/commit/ae83c6b7fd83a5906e016a32027c1bcd792a624e) updates the 'null' variants of the DebugLib macros (used when MDEPKG_NDEBUG is defined) so that they explicitly discard their parameters using `if (FALSE)` code blocks. These are understood as marking the contained code as referenced but unused by all supported compilers. This avoids the need for additional MDEPKG_NDEBUG dependent code in c files, to conditionally hide static methods or functions which are only used in debug macros. Now, such code can and must be removed.
This commit updates the relevant MDEPKG_NDEBUG code in c files throughout edk2-platforms (there are only some 20 instances).
We also fix a couple of cases where the wrapped variables …

GLOBAL: Align MDEPKG_NDEBUG dependent code with edk2 debug macro changes

---

Platform/ARM/SgiPkg/SgiPlatformMm.dsc.inc

commit 8bc44608b8ea ("MdeModulePkg: Add ImagePropertiesRecordLib") makes build fail. This patch adds ImpagePropertiesRecordLib and related libraries to fix the build.

ARM/SgiPkg: fix build failure on SgiPlatformMm

---

Platform/Intel/MinPlatformPkg/Library/SerialPortTerminalLib/SerialPortTerminalLib.c

CodeQL is reporting Pointless comparison of unsigned value to zero.
Signed-off-by: jasonc4 <v-jaschen@microsoft.com>
Cc: Reviewer Aaron Pop <aaronpop@microsoft.com>
Cc: Reviewer Shruti Gupta <shrugupt@microsoft.com>
Ran Local CI including codeQL setting and pipeline codeQL build.
N/A

CodeQL is reporting Pointless comparison of unsigned value to zero.

---

Features/Intel/UserInterface/VirtualKeyboardFeaturePkg/VirtualKeyboardDxe/Keyboard.c

The Keyboard.c driver did not include ScanCodes like F1,F2,F12,etc. and UnicodeChars like Backspace, Tab in VK_NOTIFY NotifyList which is why these keys were not getting registered and not getting pushed in the KeyBuffer stack which resulted in undefined behavior of continuous backspace and not recognizing the relevant key push after the buffer overflow condition

Pkg-Module: Features/VirtualKeyboardDxe

---

Features/Intel/UserInterface/VirtualKeyboardFeaturePkg/VirtualKeyboardDxe/Keyboard.c

The Keyboard.c driver did not include ScanCodes like F1,F2,F12,etc. and UnicodeChars like Backspace, Tab in VK_NOTIFY NotifyList which is why these keys were not getting registered and not getting pushed in the KeyBuffer stack which resulted in undefined behavior of continuous backspace and not recognizing the relevant key push after the buffer overflow condition.

Pkg-Module: Features/VirtualKeyboardDxe PART 2

---

Platform/Qemu/SbsaQemu/Readme.md
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.fdf

Hi Maintainers,
Please find herein the second revision of this set.  Following our converstion from the first iteration, I am using a command line flag to enable RME support.  I also took the initiative of adding some documentation to avoid having to look in the configuration files to remember the exact command line option to use.
Thanks for the time,
Mathieu

[V3] SbsaQemu-rme: Add support for SBSA-rme platform

---

Platform/Ampere/JadePkg/Ac02AcpiTables/PCI-S0.Rca01.asi
Platform/Ampere/JadePkg/AcpiTables/PCI-S0.Rca01.asi

This corrects the MMIO regions mapping in ACPI to be marked as NonCacheable, aligning with the precise configuration in PCI-S0.asi.
Reported-by: Chuong Tran <chuong@os.amperecomputing.com>

JadePkg/AcpiTables: Fix mapping MMIO regions as cacheable

---

Features/ManageabilityPkg/Universal/IpmiProtocol/Pei/IpmiPpiPei.inf
Features/ManageabilityPkg/Universal/IpmiProtocol/Smm/IpmiProtocolSmm.inf

This adds recent PCDs for IPMI Serial for IpmiProtocol PEI and SMM to fix the compilation error.

ManageabilityPkg/IpmiProtocol: Fix build error due to missing PCDs

---

Platform/ARM/SgiPkg/Drivers/SmbiosPlatformDxe/Type0BiosInformation.c
Platform/ARM/SgiPkg/SgiPlatform.dsc.inc

BiosVersion value is hardcoded as "EDK II" and it appears same in SMBIOS type 0 record firmware version string. This is not meaningful, it remains unchanged across releases and it does not match the version string in the release notes.
So updated BiosVersion from “EDK II” to a format that reflects the release version, such as “RD-INFRA-YYYY.MM.DD” (e.g., “RD-INFRA-2024.09.30”).

Platform/Sgi: Add Firmware Version Support

---

Platform/Intel/build_bios.py

When running build_bios.py manually it is convenient to be able to avoid rebuilding BaseTools (which also involves re-running the BaseTools tests) on every run.
Even though the time to build BaseTools (once they are already built) and re-run the BaseTools tests is relatively small compared to the time taken to fully build any of these platforms, we may be debugging an issue which prevents a given platform from building entirely, or early, and which has nothing to do with changes in BaseTools, in which case it is convenient not to have to wait for the BaseTools tests to complete each time round the debug loop.
Local builds.
N/A

Platform/Intel: Add build_bios.py option to skip rebuilding BaseTools

---

Drivers/ASIX/Bus/Usb/UsbNetworking/Ax88772c/DriverBinding.c

Support the USB NIC whose product id is PRODUCT_AX88772B_ID.

Drivers/ASIX: Bugfix for ASIX Ax88772c driver

---

Drivers/OpTee/OpteeRpmbPkg/OpTeeRpmbFv.inf
Drivers/OpTee/OpteeRpmbPkg/OpTeeRpmbFvb.c
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc
Platform/ARM/VExpressPkg/PlatformStandaloneMm.dsc
Platform/ARM/VExpressPkg/PlatformStandaloneMm.fdf
Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.dsc
Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.fdf

This patchset fixes build failure StandaloneMm on VExporessPkg
and apply remove hob creation in StandaloneMm.
When StandaloneMm running with SPM_MM,
It passes Boot Hob list created in TF-A via transfer list according to firmware handoff spec[0].
When StandaloneMm running with FF-A,
It passes Boot Hob list created in TF-A via FF-A boot protocol[1].
For this, add related Libraries in StandaloneMm dsc file.
Links: https://github.com/FirmwareHandoff/firmware_handoff [0]
Links: https://developer.arm.com/documentation/den0077/latest/ [1]

ARM/VExpressPkg: Remove Hob creation in StandaloneMm.

---

Platform/RaspberryPi/Library/PlatformLib/PlatformLib.inf
Platform/RaspberryPi/Library/PlatformLib/RaspberryPiMem.c

Commit 991b802e8f70 ("Platform/RPi4: Allocate more space for UEFI image") reorganized the Flash Device (FD) layout to accommodate the growing size of the firmware, and reserved some additional space to be used for ACPI PCC channel data in the future.
This additional allocation was added at the end of the FD, after the varstore image, while the mapping code in PlatformLib expects the varstore related regions to live at the very end.
The upshot is that the varstore region in the FD is no longer mapped for runtime access, resulting in runtime service crashes when attempting to access the varstore from under the OS.
Fix this in PlatformLib, by extending the varstore memory region to include everything that comes after it.

Platform/RaspberryPi4: Fix EFI runtime region for varstore access

---

Platform/ARM/VExpressPkg/PlatformStandaloneMm.dsc

On FVP, the StandaloneMM Boot Firmware Volume (BFV) is not in the Flash area. Instead it is loaded in to the RAM by TF-A.
Therefore, disable the shadow copying of the BFV in StandaloneMM.

Platform/Arm/VExpressPkg: Disable shadow copying of BFV in StMM

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_request.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/advanced-issue-labeler.yml
.github/workflows/issue-assignment.yml
.github/workflows/issue-triage.yml
.github/workflows/scheduled-maintenance.yml

Brings edk2-platforms GitHub issues into parity with edk2.
---
**.github: Add GitHub issue templates**
REF: https://github.com/tianocore/edk2/discussions/5926
Adds GitHub form isssue templates for bugs, documentation requests,
and feature requests.
These files define the form structure in YAML to be rendered by
GitHub in the edk2-platforms repo issues area.
Due to the large amount of diverse content on edk2-platforms an
attempt was made to classify code areas in the best way for the
current organization of the code path in the tree. Please suggest
any corrections in the PR.
---
**.github: Add issue automation workflows**
REF: https://github.com/tianocore/edk2/discussions/5926
Adds workflows to manage labels on issues based on issue content.
This uses the same flow as already used for …

Add GitHub Issue Templates and Automation

---

Platform/AMD/AmdMinBoardPkg/Library/PeiBoardInitPreMemLib/PeiMemoryInit.c

EndofAmdMemoryInfoHobPpiGuidCallBack() should only consume information from AmdMemoryInfoRange structure. Hence, the structure should not be modified
Cc: Abdul Lateef Attar <AbdulLateef.Attar@amd.com>
Cc: Abner Chang <abner.chang@amd.com>
Cc: Paul Grimes <paul.grimes@amd.com>

AmdMinBoardPkg/PeiBoardInitPreMemLib: AmdMemoryInfoRange fix

---

Platform/AMD/VanGoghBoard/Override/edk2/Fsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c

Return from FspsWrapperInitDispatchMode() if a buffer allocation fails instead of attempting to dereference the pointer.
---
Note: This is bringing a change going into the original edk2 file [here](https://github.com/tianocore/edk2/pull/6250) into this forked copy of the module.

VanGoghBoard/FspsWrapperPeim: Prevent null pointer dereference

---

Platform/AMD/OverdriveBoard/OverdriveBoard.dsc
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc
Platform/BeagleBoard/BeagleBoardPkg/BeagleBoardPkg.dsc
Platform/LeMaker/CelloBoard/CelloBoard.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Platform/SoftIron/Overdrive1000Board/Overdrive1000Board.dsc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc
Silicon/Hisilicon/Hisilicon.dsc.inc
Silicon/Marvell/Armada7k8k/Armada7k8k.dsc.inc
Silicon/Marvell/OdysseyPkg/OdysseyPkg.dsc.inc
Silicon/NXP/NxpQoriqLs.dsc.inc
Silicon/Phytium/PhytiumCommonPkg/PhytiumCommonPkg.dsc.inc
Silicon/TexasInstruments/Omap35xxPkg/Omap35xxPkg.dsc

PcdRelocateVectorTable was explicitly set to FALSE (the default value) for several platforms.
Additionally, BeagleBoard/Omap set a value for PcdCpuVectorBaseAddress which was never used because PcdRelocateVectorTable was set to false.
Get rid of these bogus Pcd settings before dropping the Pcds in edk2.

Various Arm platforms: minor Pcd cleanup

---

Platform/AMD/OverdriveBoard/OverdriveBoard.dsc
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc
Platform/BeagleBoard/BeagleBoardPkg/BeagleBoardPkg.dsc
Platform/LeMaker/CelloBoard/CelloBoard.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Platform/Socionext/DeveloperBox/DeveloperBox.dsc.inc
Platform/Socionext/SynQuacerEvalBoard/SynQuacerEvalBoard.dsc
Platform/SoftIron/Overdrive1000Board/Overdrive1000Board.dsc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc
Silicon/Hisilicon/Hisilicon.dsc.inc
Silicon/Marvell/Armada7k8k/Armada7k8k.dsc.inc
Silicon/Marvell/OdysseyPkg/OdysseyPkg.dsc.inc
Silicon/NXP/NxpQoriqLs.dsc.inc
Silicon/Phytium/PhytiumCommonPkg/PhytiumCommonPkg.dsc.inc

ArmDisassemblerLib is no longer used, and will be removed from edk2. So drop all references to it across the repo.

Platform,Silicon: Remove references to ArmDisassemblerLib

---

Platform/ARM/VExpressPkg/PlatformStandaloneMm.dsc
Platform/BeagleBoard/BeagleBoardPkg/PrePi/PeiUniCore.inf
Platform/Intel/AlderlakeOpenBoardPkg/AlderlakePRvp/OpenBoardPkg.dsc
Platform/Intel/CometlakeOpenBoardPkg/CometlakeURvp/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/AspireVn7Dash572G/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/GalagoPro3/OpenBoardPkg.dsc
Platform/Intel/KabylakeOpenBoardPkg/KabylakeRvp3/OpenBoardPkg.dsc
Platform/Intel/SimicsOpenBoardPkg/SecCore/SecMain.inf
Platform/Intel/TigerlakeOpenBoardPkg/TigerlakeURvp/OpenBoardPkg.dsc
Platform/Intel/WhiskeylakeOpenBoardPkg/UpXtreme/OpenBoardPkg.dsc
Platform/Intel/WhiskeylakeOpenBoardPkg/WhiskeylakeURvp/OpenBoardPkg.dsc
Platform/Intel/WhitleyOpenBoardPkg/PlatformPkg.dsc
Platform/Loongson/LoongArchQemuPkg/Sec/SecMain.inf
Platform/RISC-V/PlatformPkg/Universal/Sec/SecMain.inf
Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.dsc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Bosc/NanHuPkg/Sec/SecMain.inf
Silicon/Sophgo/SG2042Pkg/Sec/SecMain.inf

edk2 PR https://github.com/tianocore/edk2/pull/6381 updates the stack cookie mechanism per maintainer request to simplify platform usage.
This PR updates edk2-platforms to resolve the breaking change, adding StackCheckLib as a dependency to all SEC modules and removing DSC references to StackCheckLibNull as MdeLibs.dsc.inc does that globally now.
Note, this must only be merged after the aforementioned edk2 PR completes.

Update for Stack Cookie Breaking Change

---

CODEOWNERS
CONTRIBUTORS.md
Platform/AMD/XilinxBoard/ZynqMp/VirtualPkg/DeviceTree/DeviceTree.inf
Platform/AMD/XilinxBoard/ZynqMp/VirtualPkg/DeviceTree/System.dts
Platform/AMD/XilinxBoard/ZynqMp/VirtualPkg/VirtualPkg.dec
Platform/AMD/XilinxBoard/ZynqMp/VirtualPkg/VirtualPkg.dsc
Platform/AMD/XilinxBoard/ZynqMp/VirtualPkg/VirtualPkg.fdf
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.dec
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.dsc.inc
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.fdf.inc
Silicon/AMD/Xilinx/CommonPkg/CommonPkgRules.fdf.inc
Silicon/AMD/Xilinx/CommonPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.c
Silicon/AMD/Xilinx/CommonPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.h
Silicon/AMD/Xilinx/CommonPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.inf
Silicon/AMD/Xilinx/ZynqMpPkg/Library/SerialPortLib/SerialPortInternal.h
Silicon/AMD/Xilinx/ZynqMpPkg/Library/SerialPortLib/SerialPortLib.c
Silicon/AMD/Xilinx/ZynqMpPkg/Library/SerialPortLib/SerialPortLib.inf
Silicon/AMD/Xilinx/ZynqMpPkg/Library/ZynqMpLib/AArch64/ArmPlatformHelper.S
Silicon/AMD/Xilinx/ZynqMpPkg/Library/ZynqMpLib/ZynqMpLib.c
Silicon/AMD/Xilinx/ZynqMpPkg/Library/ZynqMpLib/ZynqMpLib.inf
Silicon/AMD/Xilinx/ZynqMpPkg/Library/ZynqMpLib/ZynqMpLibMem.c
Silicon/AMD/Xilinx/ZynqMpPkg/README.md
Silicon/AMD/Xilinx/ZynqMpPkg/ZynqMpPkg.dec
Silicon/AMD/Xilinx/ZynqMpPkg/ZynqMpPkg.dsc.inc
Silicon/AMD/Xilinx/ZynqMpPkg/ZynqMpPkg.fdf.inc

- Add ZynqMP Silicon package
- Add a dummy ZynqMP platform as an example
Tested on KV260

Add AMD ZynqMP Support

---

Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.dsc

On PlatformStandaloneMmPkg, the StandaloneMM Boot Firmware Volume (BFV) is not in the Flash area. Instead it is loaded in
to the RAM by optee's code.
Therefore, disable the shadow copying of the BFV in StandaloneMM.

Platform/PlatformStandaloneMmPkg/: Disable shadow copying of BFV in StMM

---

Platform/ARM/N1Sdp/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.c

An integer overflow caused a negative memory size in the SRAT tables. Add a UINT64 cast to fix.

Platform: N1Sdp: Fix integer overflow in memory affinity calculation

---

Features/Intel/OutOfBandManagement/IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c
Features/Intel/OutOfBandManagement/IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.inf

**Description:**
Currently we will hit PF# if using gPeiIpmiTransportPpiGuid function in Post Mem since nobody do migraite for the function pointer in gPeiIpmiTransportPpiGuid.
**Solution:** 
FixUp FuctionPointer in gPeiIpmiTransportPpiGuid afte MemoryDiscovered

IpmiFeaturePkg: FixUp FuctionPointer in gPeiIpmiTransportPpiGuid after MemoryDiscovered

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/code_first.yml
.github/ISSUE_TEMPLATE/documentation_request.yml
.github/ISSUE_TEMPLATE/feature_request.yml

The EDK II Code First process is being revised to align with GitHub.
The actual process changes will be made to the process page on the TianoCore wiki:
https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Code-First-Process
These changes:
- Remove the "code first" checkbox from existing forms.
- Add a "code first" issue form that is used to submit issues tracking code first changes.
The primary template filled in for code first changes is included with no change from the prior template.
Note: This change is made in edk2-platforms so its issue submission process is consistent with edk2 but most code first items are expected to use an edk2 repo issue as their primary tracking issue.

.github: Add EDK II Code First form

---

Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Marvell/OdysseyPkg/OdysseyPkg.fdf
Silicon/Marvell/OdysseyPkg/Library/OdysseyLib/OdysseyLib.c
Silicon/Marvell/OdysseyPkg/OdysseyPkg.dsc.inc

Update OdysseyPkg files to use PeilessSec module which has superseded PrePi

Marvell/OdysseyPkg: Convert to using PeilessSec

---

Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Silicon/Marvell/Drivers/Fdt/FdtPlatformDxe/FdtPlatform.c

While test building an unrelated change, I noticed I couldn't build the NOOPT target with clang on OdysseyPkg. These changes make that possible.

Silicon/Marvell: enable clang and NOOPT builds for OdysseyPkg

---

Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc

This fixes the compilation error since some files are moved or changed in edk2 repo.

AmpereAltraPkg: Fix compilation error

---

Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/SgiPkg/SgiPlatform.dsc.inc
Platform/ARM/SgiPkg/SgiPlatformMm.dsc.inc
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc
Platform/ARM/VExpressPkg/PlatformStandaloneMm.dsc
Platform/BeagleBoard/BeagleBoardPkg/BeagleBoardPkg.dsc
Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.dsc
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc
Silicon/Marvell/Armada7k8k/Armada7k8k.dsc.inc
Silicon/NXP/NxpQoriqLs.dsc.inc
Silicon/Phytium/PhytiumCommonPkg/PhytiumCommonPkg.dsc.inc

This change adapts to the new locations of the SMC, SVC, and FFA libraries following their relocation from ArmPkg.
The EDK2 updates are introduced in the following PR:
https://github.com/tianocore/edk2/pull/10929.

Update Library Paths for SMC/SVC/FFA

---

Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/Morello/MorelloPlatform.dsc.inc
Platform/ARM/N1Sdp/N1SdpPlatform.dsc
Platform/ARM/SgiPkg/SgiPlatform.dsc.inc
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Phytium/DurianPkg/DurianPkg.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc

Since UEFI requires AArch64 to support FP/NEON, the Pcd to decide whether to enable (or disable trapping of) those instructions has changed to be ARM-only in edk2, and the enabling to be unconditional for AArch64.
So drop the explicit setting to 1 for all AArch64 platforms, and move the setting to a .ARM section for the one dual-architecture platform in the tree (Juno)
(This change is needed after [#10931](https://github.com/tianocore/edk2/pull/10931) is merged.)

Various Arm/AArch64 platforms: make PcdVFPEnabled AArch32-only

---

Platform/ARM/N1Sdp/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.c
Platform/ARM/N1Sdp/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.h

The N1SDP board has two MMU-600 devices used for PCIe and CCIX. Similar, configuration exists for the second (remote) chip. The N1SDP firmware is describing the SMMUv3 nodes in the IORT table.
This patch adds support for describing the PMCG nodes for these SMMUs.

Platform/ARM/N1SDP: Add PMCG nodes for SMMU

---

Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.c

The configuration manager repository should be initialized first before installing protocols. The current implementation does the opposite. If the repo initialization fails after the protocol is already installed and the protocol is accessed without a backing repo, this would result in crashes.
This fix makes sure the correct order is used to avoid such issues

VExpressPkg: Install protocol after initializing repository in CfgMgr

---

Features/Intel/Network/NetworkFeaturePkg/Include/NetworkFeature.dsc

The NetworkPcds.dsc.inc include file have been broken out into 2 separate files: NetworkFixedPcds.dsc.inc and NetworkDynamicPcds.dsc.inc
Fix NetworkFeaturePkg so it includes the correct paths.

NetworkFeaturePkg: Fix Include Paths

---

Platform/Intel/MinPlatformPkg/Include/Dsc/CoreDxeLib.dsc

StandaloneMmCoreEntryPoint.inf has moved from StandaloneMmPkg to MdePkg. Update the library path to the new location.

MinPlatformPkg: Fix StandaloneMmCoreEntryPoint library path

---

Platform/Intel/KabylakeOpenBoardPkg/AspireVn7Dash572G/OpenBoardPkgPcd.dsc

The PcdTcgPhysicalPresenceInterfaceVer PCD is used by both PEI and DXE modules and therefore needs to be defined to support both the IA32 and X64 architectures. Currently it is only defined for X64.

KabylakeOpenBoardPkg/AspireVn7Dash572G: Fix Build

---

Platform/Intel/build_bios.py

Add an optional --verbose/-v argument to build_bios.py that enables verbose log output in BaseTools. This can aid debugging of build issues in some cases.

Intel-Platforms: Add Verbose Argument

---

Readme.md

Clarify what "actively maintained" means.
While we're here, get rid of the clearly not actively maintained list of supported platforms.

Readme.md: expectations update

---

Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi3/RPi3.fdf
Platform/RaspberryPi/RPi4/RPi4.dsc
Platform/RaspberryPi/RPi4/RPi4.fdf

HTTP boot has been broken on RPi ever since the PixieFail CVE fixes were applied, as the TCP driver now relies on Hash2Dxe (and the EFI RNG protocol) to produce cryptographically strong sequence numbers.
Add the missing driver to restore HTTP boot functionality.

Platform/RaspberryPi: Add missing Hash2Dxe for HTTP boot

---

Silicon/Intel/IntelSiliconPkg/IntelSiliconPkg.dec

The library class is currently missing in the `LibraryClasses` section.

IntelSiliconPkg: Add IntelVTdPeiDxeLib to DEC LibraryClasses

---

Platform/ARM/Drivers/FdtPlatformDxe/FdtPlatform.c
Platform/ARM/Drivers/FdtPlatformDxe/FdtPlatform.h
Platform/ARM/Drivers/FdtPlatformDxe/ShellDumpFdt.c
Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/N1Sdp/N1SdpPlatform.dsc
Platform/ARM/SgiPkg/SgiPlatform.dsc.inc
Platform/RaspberryPi/Drivers/FdtDxe/FdtDxe.c
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Silicon/ARM/NeoverseN1Soc/Library/N1SdpNtFwConfigPei/NtFwConfigPei.c
Silicon/Marvell/Drivers/Fdt/FdtClientDxe/FdtClientDxe.c
Silicon/Marvell/Drivers/Fdt/FdtPlatformDxe/FdtPlatform.c
Silicon/Marvell/OdysseyPkg/OdysseyPkg.dsc.inc

EmbeddedPkg FdtLib is getting deleted, so upgrade affected platforms that actually build.
Note: sgi575 appears broken due to unrelated ArmFfaLib changes, but I fixed the things that seem related to FdtLib.

Various platforms: Migrate to MdePkg BaseFdtLib

---

Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type08/PlatformPortConnectorFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type09/PlatformSystemSlotFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type11/PlatformOemStringFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type16/PlatformPhysicalMemoryArrayFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type17/PlatformMemoryDeviceFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type19/PlatformMemoryArrayMappedAddressFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type24/PlatformHardwareSecurityFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type38/PlatformIpmiDeviceFunction.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type41/PlatformOnboardDevicesExtendedFunction.c
Silicon/Ampere/AmpereAltraPkg/Drivers/RootComplexConfigDxe/RootComplexConfigDxe.c
Silicon/Ampere/AmpereAltraPkg/Drivers/SystemFirmwareUpdateDxe/SystemFirmwareUpdateDxe.c

Actually this was a part of findings fixed by https://github.com/tianocore/edk2/pull/6424
But when I tried to build /Ampere/JadePkg/Jade.dsc  I've got a bunch of other  [-Werror=maybe-uninitialized] warnings.

Fix hii opcode handle leak

---

Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.fdf
Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc

Since there is no proper library related to SEC phase for VExpressPkg, it fails to build with SEC & PEI phase.
Also use EDK2_SKIP_PEICORE to determine if PeilessSec or the SEC & PEI phase build is desired.
Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>

Platoform/ARM/VExpressPkg: fix build failure for SEC & PEI phase

---

Platform/Intel/MinPlatformPkg/Include/Dsc/CorePeiLib.dsc

Set the appropriate CpuExceptionHandlerLib library instance for PEIM and PEI_CORE in MinPlatformPkg.

MinPlatformPkg: Update CpuExceptionHandlerLib instance for PEI

---

Platform/Intel/MinPlatformPkg/Include/Fdf/CorePostMemoryInclude.fdf
Platform/Intel/MinPlatformPkg/Include/Fdf/CorePreMemoryInclude.fdf

Some platforms do not dispatch FvPostMemory on S3 resume. Moving this PEIM to FvPreMemory ensures performance measurement during S3 resume works on all implementations.

MinPlatformPkg: Move FirmwarePerformancePei to FvPreMemory

---

Platform/ARM/SgiPkg/SgiPlatformMm.dsc.inc

With commit b534cabbdac4eed002cbd84f31bcad584002f731 "Extend MM communication v3 to ARM and UEFI variable modules" in edk2 MmServicesTableLib is added to Packages of ArmFfaStandaloneMmCoreLib.
Move the instance of MmServicesTableLib out of MM_STANDALONE

Platform/ARM/SgiPkg: Fix StMM build failure

---

Platform/Qemu/SbsaQemu/SbsaQemu.dsc

Simple fix to get platform buildable again

SbsaQemu: Add missing VirtNorFlashDeviceLib instance

---

Platform/AMD/TurinBoard/Override/edk2/MdeModulePkg/MdeModulePkg.dsc
Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/Morello/MorelloPlatform.dsc.inc
Platform/ARM/N1Sdp/N1SdpPlatform.dsc
Platform/ARM/SgiPkg/SgiPlatform.dsc.inc
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/BeagleBoard/BeagleBoardPkg/BeagleBoardPkg.dsc
Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Qemu/SbsaQemu/SbsaQemu.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraLinuxBootPkg.dsc.inc
Silicon/Ampere/AmpereAltraPkg/AmpereAltraPkg.dsc.inc
Silicon/Marvell/Armada7k8k/Armada7k8k.dsc.inc
Silicon/NXP/NxpQoriqLs.dsc.inc
Silicon/Phytium/PhytiumCommonPkg/PhytiumCommonPkg.dsc.inc

ArmMmuLib is moved from ArmPkg to UefiCpuPkg, update ArmMmuLib path for all platforms to adapt EDK2 change:
https://github.com/tianocore/edk2/pull/11017

Update ArmMmuLib library path

---

Platform/BeagleBoard/BeagleBoardPkg/Library/MemoryInitPeiLib/MemoryInitPeiLib.inf
Platform/RaspberryPi/Library/MemoryInitPeiLib/MemoryInitPeiLib.inf
Silicon/Ampere/AmpereAltraPkg/Library/MemoryInitPeiLib/MemoryInitPeiLib.inf
Silicon/Marvell/Armada7k8k/Library/Armada7k8kMemoryInitPeiLib/Armada7k8kMemoryInitPeiLib.inf
Silicon/NXP/Library/MemoryInitPeiLib/MemoryInitPeiLib.inf

Commit 7516ab83ff67 ("Update ArmMmuLib library path") did what it says, but some packages in the tree have their own modules making use of ArmMmuLib, without previously having declared a dependency on UefiCpuPkg.
Add the missing dependencies.

Various packages: add missing UefiCpuPkg dependency for ArmMmuLib

---

Silicon/Intel/IntelSiliconPkg/Include/IndustryStandard/FirmwareInterfaceTable.h

Type 0x1E entry allows BIOS to locate VAB Authorization Code Patch manifest and requests security controller to authorize and update.

IntelSiliconPkg: Define FIT Record 0x1E

---

Platform/Intel/MinPlatformPkg/FspWrapper/MpInfo2HobPei/MpInfo2HobPei.c

If the MpInformation2Hob already exists, then MpInfo2HobPei will return a uninitialized Status value. This change fixes this issue by explicitly initializing Status to EFI_SUCCESS.

MinPlatformPkg: Fix use of uninitialized variable in MpInfo2HobPei

---

Platform/Intel/AlderlakeOpenBoardPkg/AlderlakePRvp/OpenBoardPkgBuildOption.dsc
Platform/Intel/AlderlakeOpenBoardPkg/Policy/Library/DxeSiliconPolicyUpdateLib/DxeSiliconPolicyUpdateLate.c
Silicon/Intel/AlderlakeSiliconPkg/Product/Alderlake/SiPkgBuildOption.dsc

- Adds `[BuildOptions]` entries needed to compile with Clang
- Fix return type of the SiliconPolicyUpdateLate() function

Alderlake: Add support for the Clang compiler

---

Platform/Intel/AlderlakeOpenBoardPkg/AlderlakePRvp/OpenBoardPkgBuildOption.dsc
Silicon/Intel/AlderlakeSiliconPkg/Product/Alderlake/SiPkgBuildOption.dsc

Alderlake: Add 4K FILEALIGN for Runtime DXE & SMM Drivers

---

Platform/Sophgo/SG2042_EVB_Board/SG2042.dsc

Following commit https://github.com/tianocore/edk2/commit/8aad683e59dc5342a4c9b8bc3d84133d4b1896f6, EmbeddedPkg FdtLib has been replaced by MdePkg BaseFdtLib. This PR ensures SG2042 continues to build successfully. 
This is a compatibility fix only; no functional changes are introduced.

SG2042: use MdePkg BaseFdtLib

---

Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.c
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManagerDxe.inf
Platform/ARM/VExpressPkg/Library/ArmVExpressWatchdogLib/ArmVExpressWatchdogLib.c
Platform/ARM/VExpressPkg/Library/ArmVExpressWatchdogLib/ArmVExpressWatchdogLib.inf

GICv5 uses different interrupt numbering to previous GIC versions. ConfigurationManager now updates PlatformRepositoryInfo and the relevant PCDs if GICv5 is detected.
To ensure correct dependencies between WatchdogDxe and ConfigurationManager, this commit introduces ArmVExpressWatchdogArchLib.
This change depends on the GICv5 driver pull request at https://github.com/tianocore/edk2/pull/11240

Platform: VExpressPkg: Add GICv5 support

---

Features/Intel/Network/NetworkFeaturePkg/Include/NetworkFeature.dsc

When NETWORK_ENABLE is TRUE and NETWORK_ALLOW_HTTP_CONNECTIONS is TRUE,
NetworkPkg/NetworkFixedPcds.dsc.inc specifies
gEfiNetworkPkgTokenSpaceGuid.PcdAllowHttpConnections as TRUE.
But the PCD is set under [PcdsFixedAtBuild] section. The build.py will complain the following error:
Pcd (gEfiNetworkPkgTokenSpaceGuid.PcdAllowHttpConnections) defined in DSC is not declared in DEC files referenced
in INF files in FDF. Arch: ['IA32']
The commit fixes the failure by only setting the PCD in the [PcdsFixedAtBuild.$(DXE_ARCH)] section.

NetworkFeaturePkg: fix build failure

---

Platform/ADLINK/ComHpcAltPkg/Library/OemMiscLib/OemMiscLib.c
Platform/ASRockRack/AltraBoardPkg/Library/OemMiscLib/OemMiscLib.c

Since the ADLINK Ampere Development Kit and ASRock Rack ALTRAD8 boards aren't full systems, we don't know what type of chassis they'll be installed in. So set the chassis type to unknown.

Platform/{ADLINK,ASRockRack}: Set SMBIOS chassis type to unknown

---

Platform/Qualcomm/RB3Gen2/RB3Gen2.dsc
Silicon/Qualcomm/KodiakPkg/Library/KodiakLib/KodiakHelper.S
Silicon/Qualcomm/KodiakPkg/Library/KodiakLib/KodiakHelper.h

Many Qualcomm targets use Gunyah as a firmware-launched hypervisor, making EL2 unavailable for Non-secure firmware and operating systems, preventing use of alternative hypervisors.
Quoting Arm Base Boot Requirements here:
```
6.3.1.1. UEFI boot at EL2
Systems must boot UEFI at EL2, to enable the installation of a hypervisor
or a virtualization-aware operating system.
```
So lets use a TZ SMC call supported on these Qcom targets to clean up EL2/Gunyah configuration and transition to booting edk2 (UEFI) at EL2 exiting Gunyah. All the SMMU configuration gets cleaned up and handed over in EL2 in bypass mode. The edk2 is able to configure EL2 MMU/SMMU as you would expect on an Arm silicon executing edk2 in EL2.
Apart from that there are some build fixes included to follow library paths in …

Platform/Qualcomm/RB3Gen2: Enable booting edk2 at EL2

---

Platform/Intel/MinPlatformPkg/PlatformInit/Library/SecBoardInitLibNull/SecBoardInitLibNull.inf

SecBoardInitLibNull does not requires any package except MdePkg.dec
Signed-off-by: PaddyDeng <paddydeng@ami.com>

MinPlatformPkg: Remove unnecessary packages

---

Silicon/Ampere/AmpereAltraPkg/Drivers/CpuConfigDxe/CpuConfigStrings.uni
Silicon/Ampere/AmpereAltraPkg/Drivers/PlatformInfoDxe/PlatformInfoStrings.uni

Improve some HII strings related to ANC and SLC cache.
Clarify in the help string for ANC mode that 'ANC' means Ampere NUMA Control. And simplify the rest of the string to avoid repetition.
Replace '$' with the word 'Cache'. While '$' might be a common shorthand in the industry, it confuses other people.
In the platform board information page, the help string was wrong: it doesn't indicate SLC as L3 Cache, but simply the amount of System Level Cache.

Silicon/Ampere: Improve SLC cache and ANC strings

---

Features/Ext4Pkg/Ext4Dxe/Collation.c
Features/Ext4Pkg/Ext4Dxe/Ext4Dxe.inf

This PR addresses the usage of gEfiUnicodeCollationProtocolGuid, which has been deprecated, replacing it with the newer version of gEfiUnicodeCollation2ProtocolGuid, which offers enhanced language support and improved extensibility.

Deprecate gEfiUnicodeCollationProtocolGuid

---

Platform/ADLINK/ComHpcAltPkg/Library/PCF8563RealTimeClockLib/PCF8563RealTimeClockLib.inf
Platform/ASRockRack/AltraBoardPkg/Library/ISL1208RealTimeClockLib/ISL1208RealTimeClockLib.inf
Platform/Ampere/JadePkg/Library/PCF85063RealTimeClockLib/PCF85063RealTimeClockLib.inf
Platform/Loongson/LoongArchQemuPkg/Library/LsRealTimeClockLib/LsRealTimeClockLib.inf
Silicon/Maxim/Library/Ds1307RtcLib/Ds1307RtcLib.inf

RealTimeClockLib header has been moved to MdeModulePkg in https://github.com/tianocore/edk2/pull/11362
So the package has been added to the relevant INF files.

Support RealTimeClockLib header move to MdeModulePkg

---

Platform/Qualcomm/RB3Gen2/DeviceTree/Dummy.dts
Platform/Qualcomm/RB3Gen2/DeviceTree/DummyDeviceTree.inf
Platform/Qualcomm/RB3Gen2/DeviceTree/UserDTB.inf
Platform/Qualcomm/RB3Gen2/RB3Gen2.dsc
Platform/Qualcomm/RB3Gen2/RB3Gen2.fdf
Platform/Qualcomm/RB3Gen2/Readme.md
Silicon/Qualcomm/Drivers/QcomUfsHcDxe/QcomUfsHcDxe.c
Silicon/Qualcomm/Drivers/QcomUfsHcDxe/QcomUfsHcDxe.inf
Silicon/Qualcomm/QcomPlatformPkg/QcomPlatformPkg.dec

Add support for UFS driver on RB3Gen2 platform. This driver is registered as non-discoverable device over PCIe I/O protocol supported by UFS pass through host controller driver framework.
This UFS driver assumes that the prior stage XBL on Qcom SoCs has fully initialized the UFS controller where the primary boot medium is UFS flash on Qcom SoCs. Given that the initialization is skipped here and only the UFS controller MMIO address space is registered for UFS I/O to take place.
With UFS storage driver in place, we are able to load the EFI payload on RB3Gen2 platform, following are the logs:
```
EFI stub: EFI_RNG_PROTOCOL unavailable
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
EFI stub: Generating empty DTB
EFI stub: Exiting boot services...
```
The next step is to …

Platform/Qualcomm/RB3Gen2: Add UFS driver and DTB support

---

Platform/ASRockRack/AltraBoardPkg/Library/ISL1208RealTimeClockLib/ISL1208RealTimeClockLib.inf

RealTimeClockLib.h moved from EmbeddedPkg to MdeModulePkg some time ago.

Ampere/ASRockRack: handle move of RealTimeClockLib.h

---

Platform/ARM/JunoPkg/ArmJuno.dsc
Platform/ARM/JunoPkg/PlatformStandaloneMm.dsc

Fix build failure of JunoPkg:
- ArmFfaLib is located from ArmPkg to MdeModulePkg and it was included in ArmVExpress.dsc.inc file So remove it.
- While integrating the PlatformStandaloneMm.dsc.inc, there was a mistaken for missing !endif

Platform/ARM/JunoPkg: fix Juno build failure

---

Features/Intel/OutOfBandManagement/IpmiFeaturePkg/Library/IpmiBaseLib/IpmiBaseLib.c
Features/Intel/OutOfBandManagement/IpmiFeaturePkg/Library/SmmIpmiBaseLib/SmmIpmiBaseLib.c

Add missing EFIAPI in implementation of UEFI event notification functions.

OutOfBandManagement/IpmiFeaturePkg: Add missing EFIAPI

---

Platform/ADLINK/ComHpcAltPkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheData.c
Platform/ADLINK/ComHpcAltPkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheFunction.c
Platform/ADLINK/ComHpcAltPkg/Library/OemMiscLib/OemMiscLib.c
Platform/ARM/JunoPkg/SmbiosPlatformDxe/SmbiosPlatformDxe.c
Platform/ARM/SgiPkg/Drivers/SmbiosPlatformDxe/Type4ProcessorInformation.c
Platform/ARM/SgiPkg/Drivers/SmbiosPlatformDxe/Type7CacheInformation.c
Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.c
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.h
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManager.uni
Platform/ARM/VExpressPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManagerDxe.inf
Platform/ASRockRack/AltraBoardPkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheData.c
Platform/ASRockRack/AltraBoardPkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheFunction.c
Platform/ASRockRack/AltraBoardPkg/Library/OemMiscLib/OemMiscLib.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheData.c
Platform/Ampere/JadePkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheFunction.c
Platform/Intel/Vlv2TbltDevicePkg/SmBiosMiscDxe/MiscProcessorCacheFunction.c
Platform/RaspberryPi/Drivers/PlatformSmbiosDxe/PlatformSmbiosDxe.c
Silicon/Marvell/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c
Silicon/Phytium/FT2000-4Pkg/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c
Silicon/Sophgo/SG2042Pkg/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c

Platform support for DynamicTablesPkg SMBIOS generation, currently in review at https://github.com/tianocore/edk2/pull/11409.
This pull request contains changes for VExpressPkg to use the new generators. It also contains patches for a number of other platforms to use the new SMBIOS structure definitions for cache size and AArch64 CPU ID; I addressed all users I could find.

DynamicTablesPkg: Add SMBIOS generation

---

Platform/ARM/VExpressPkg/ArmVExpress.dsc.inc
Platform/Marvell/OdysseyPkg/OdysseyPkg.dsc
Platform/Phytium/DurianPkg/DurianPkg.dsc
Platform/RaspberryPi/RPi3/RPi3.dsc
Platform/RaspberryPi/RPi4/RPi4.dsc
Silicon/AMD/Xilinx/CommonPkg/CommonPkg.dsc.inc

As edk2 introduce PeilessSecMeasureLib [0],
PeilessSec requires to link PeilessSecMeasureLib.
Set the default PeilessSecMeasureLib with PeilessSecMeasureNullLib.
Link: https://github.com/tianocore/edk2/pull/11344 [0]
Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>

Platform, Silicon: add default PeilessSecMeasureLib

---

Platform/ASRockRack/AltraBoardPkg/Drivers/SmbiosPlatformDxe/Type07/PlatformCacheData.c

Fix the cache size value in the SMBIOS Type 7 table. The first value is the 15-bit size, not the complete 16-bit value including the granularity.

Platform/ASRockRack: Fix cache size value
